### ISSUE TITLE
an error about the use of exp_lr_scheduler

### ISSUE THREAD

**Issue by kxdQAQ** [amoudgl/pygoturn#16]
Hello, thank you for your great work, but I find an error about exp_lr_scheduler. For example, when itr > 0 and itr % args.lr_decay_step == 0, the lr should become 0.1*lr. However, the lr will continue decreasing until done==1. And the number of decreasing is related with batchsize. The more batchsize, the more the number of decreasing. So I set exp_lr_scheduler after “if done:”.

**Comment by amoudgl** [comment]
Yes, you are correct. Could you please send a PR for this?

**Comment by kxdQAQ** [comment]
![code](https://user-images.githubusercontent.com/29788026/38976685-8e906eb0-43e4-11e8-920f-f658b0bc41d8.jpg)

**Comment by amoudgl** [comment]
Yes, I got it. I was wondering if you would be interested in contributing to this project by sending a pull request (PR) for this update. Let me know if you are interested otherwise I would make the commit myself.

**Comment by amoudgl** [comment]
@kxdQAQ I am making the commit, would add you as a coauthor.

**Comment by kxdQAQ** [comment]
OK, thank you very much.

**Comment by amoudgl** [comment]
Thanks for your contribution!
