### ISSUE TITLE
ImageNet training

### ISSUE THREAD

**Issue by amoudgl** [amoudgl/pygoturn#2]
Add ImageNet training to GOTURN. 

- [x] Add ImageNet loader to `datasets.py`. 
- [x] Filter ImageNet dataset by removing images with objects covering 66% of the image size.
- [x] Implement random cropping (motion smoothness model) on the fly. 
- [x] Update `train.py` with ImageNet training.

**Comment by devyhia** [comment]
@amoudgl We are currently working on training using the ImageNet dataset and benchmarking the trained models. I am working with three other classmates (and willing to contribute to your project) to get a working GOTURN model. Let me know if you need help with some of these tasks.

**Comment by amoudgl** [comment]
@devyhia That's great. Please invite your classmates who are willing to contribute, to the Slack channel. We can divide the work systematically there and hence avoid the scenario of multiple people working on the same task.
