### ISSUE TITLE
Model Load Error

### ISSUE THREAD

**Issue by herleeyandi** [amoudgl/pygoturn#20]
Hi I suggest to change `test.py` line 37 to `self.model.load_state_dict(checkpoint)` otherwise it will be an error while loading the `final_model.pth` .
```
Traceback (most recent call last):
  File "demo.py", line 100, in <module>
    main(args)
  File "demo.py", line 70, in main
    device)
  File "/home/mspl/pygoturn/src/test.py", line 39, in __init__
    self.model.load_state_dict(checkpoint['state_dict'])
```

**Comment by amoudgl** [comment]
Hi, it looks like you are using the latest code with the old version of checkpoint. I changed the format of checkpoint in my recent commits. Please redownload the pre-trained model, it should work as expected.
