### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by junliang230** [amoudgl/pygoturn#22]
pretrained model file seems to have been damaged？
could you fix it, thanks

**Comment by 15307130116** [comment]
I met the same problem

**Comment by amoudgl** [comment]
Hi, there were two links to pretrained model in README. I updated one link in my last commit (the one in bold) while the other link was wrong (probably from where you downloaded the model). I have fixed that, both links now point to the correct file.

**Comment by 15307130116** [comment]
Many thanks for your reply in time! But in fact the file in the new link is broken, too. Could you please fix the problem?

**Comment by amoudgl** [comment]
Oh, that's odd. I just downloaded the file from the given link and executed demo script, it worked fine. Are you not able to download the file itself or the downloaded file (426M) doesn't work?

**Comment by 15307130116** [comment]
Thank you for your reply! It seems that the downloaded file is broken...


-----原始邮件-----
发件人:"Abhinav Moudgil" <notifications@github.com>
发送时间:2019-04-04 21:29:55 (星期四)
收件人: amoudgl/pygoturn <pygoturn@noreply.github.com>
抄送: JinGye <15307130116@fudan.edu.cn>, Comment <comment@noreply.github.com>
主题: Re: [amoudgl/pygoturn] pretrained model (#22)



Oh, that's odd. I just downloaded the file from the given link and executed demo script, it worked fine. Are you not able to download the file itself or the downloaded file (426M) doesn't work?

**Comment by amoudgl** [comment]
Alright! I'll close this issue for now. Feel free to reopen in case of any further issues.

**Comment by renxinhe** [comment]
Hi. I ran into the same issue with the downloaded tar file from [this link](https://drive.google.com/a/fb.com/uc?id=1szpx3J-hfSrBEi_bze3d0PjSfQwNij7X&export=download). When I try to extract the tar file, I got an error saying it's not a tar file.
```
$ tar -xvf pytorch_goturn.pth.tar 
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors
```

Here's the SHA256 checksum of my downloaded file. Could you please help verify that the file is the same? Thanks!
```
$ shasum -a 256 pytorch_goturn.pth.tar 
cfd8dbd26203fbd0811045f9a3eb66f27f71e7d637e61ddfed2b2847d6dc6232  pytorch_goturn.pth.tar
```

**Comment by renxinhe** [comment]
I think I know what's going on here. The tar file is in fact the pth model file itself. There's no need to extract it. Could you please rename the file extension or add a line of comment in the readme to clarify this?
