### ISSUE TITLE
Training content

### ISSUE THREAD

**Issue by madan0511** [amoudgl/pygoturn#25]
Can you please tell me what are the training images ( size ) that the pretrained-model has been trained on?

**Comment by amoudgl** [comment]
The model has been trained on approximately 0.25 million images (~58G). Each image has the size 224x224.

**Comment by Ghost051196** [comment]
How can i get those images?. Do you have any link?

**Comment by amoudgl** [comment]
Please refer to [Prepare Training Data](https://github.com/amoudgl/pygoturn#prepare-training-data) in README for more details.
